### ISSUE TITLE
Agressive testing

### ISSUE THREAD

**Issue by nibalizer** [IBM/nodejs-express-app#85]
Hi Folks, 

Really like this starter kit. Used it a couple times now. 

Couple points:

1) Somewhere (i guess on npm install?) it installs a `nyt mocha` pre-commit hook without asking me. This is (to me) a step too far and I'd want that to clearly say it's doing it and give me a chance to deny

2) It turns on by default voting coverage tests that fail by default and linting errors that fail by default.

These two together mean my first experince with this thing is git clone, npm install, <very small change>, git commit -> boom, errors I didn't expect.

How do you feel about making this more opt-in?

Thanks in advance!

**Comment by gee4vee** [comment]
Hi thanks for the feedback. Will be looking at this.

**Comment by jmeis** [comment]
Hi @nibalizer -- thanks for the feedback!

The pre-commit hooks and coverage checks are configured in the **package.json** here:

https://github.com/IBM/nodejs-express-app/blob/development/package.json#L17

You can remove husky and/or edit the configurations there to make the code not be so aggressive when it comes to enforcing linting/testing/coverage policies. I don't think we have this documented anywhere, so it might be a good idea for us to add that somewhere in the README.

**Comment by nibalizer** [comment]
The linting and coverage does work on the default application, sorry I was wrong about that. I added code myself and ran 'prettier' on the server.js which is why I got failures. I still do think a pre-commit hook is aggressive.. especially for a coverage test. I use this to bang out quick simple apps and I don't write tests for them, so I'm probably not the ideal user, even if I am one user.

**Comment by gee4vee** [comment]
@nibalizer you pretty much handled things as expected, but we're going to update our README to give clearer guidelines on how to deal with the code coverage and linting. Out of the box we do strive for aggressive coverage and linting but will make it clearer how to adjust.

**Comment by gee4vee** [comment]
Readme updates are merged. Closing this.
